const QUESTIONS = [
  // ---- Bullwhip / Supply Chain (from 2025 & 2023/24 exams + extra) ----
  {topic:"Bullwhip Effect", q:"The \"bullwhip effect\" in a supply chain, often demonstrated by the Beer Game, refers to:", options:["The phenomenon where consumer demand for a product decreases as it moves up the supply chain.","A surge in production efficiency and accuracy as orders are processed from retailer to manufacturer.","The amplification of demand variability as one moves up the supply chain from the retailer to the manufacturer.","A planned and controlled increase in inventory at each stage of the supply chain to prevent stockouts."], answer:2, explain:"The bullwhip effect is the progressive amplification of order variability as you move upstream from retailer to manufacturer to supplier."},
  {topic:"Bullwhip Effect", q:"Which of the following is a primary cause of the bullwhip effect, as illustrated in the Beer Game?", options:["Perfect and instantaneous communication between all levels of the supply chain.","Stable and predictable consumer demand with no fluctuations.","Lack of visibility into end-customer demand and long lead times between ordering and receiving goods.","The immediate fulfillment of all orders at every stage of the supply chain without any delays."], answer:2, explain:"Poor visibility into real end-customer demand combined with long lead times causes each tier to over-react and over-order."},
  {topic:"Bullwhip Effect", q:"A key takeaway from playing the Beer Game is that to mitigate the bullwhip effect, companies should focus on:", options:["Increasing their inventory levels at every stage to buffer against any possible demand shifts.","Making ordering decisions in isolation, based only on the orders received from the immediate downstream partner.","Improving information sharing and collaboration across the entire supply chain to enhance visibility of actual end-consumer demand.","Lengthening lead times to allow for more careful and deliberate order processing."], answer:2, explain:"Sharing real point-of-sale/demand data and collaborating across the chain is the standard remedy, not stockpiling or acting in isolation."},
  {topic:"Bullwhip Effect", q:"Which of these is NOT a recognized cause of the bullwhip effect?", options:["Order batching / large lot sizes","Promotional price fluctuations","Perfectly shared, real-time point-of-sale data across all tiers","Free returns / order cancellation policies"], answer:2, explain:"Perfectly shared real-time POS data is the CURE for the bullwhip effect, not a cause of it."},
  {topic:"Bullwhip Effect", q:"A retailer needing 100 units/week instead orders 0-0-0-400 over four weeks. This is an example of which bullwhip cause?", options:["Demand forecast updating","Order batching","Price fluctuation","Genchi Genbutsu"], answer:1, explain:"Batching many weeks of demand into one large periodic order (order batching) creates artificial spikes upstream even though real demand is steady."},

  // ---- TPS / Lean / JIT ----
  {topic:"TPS / Lean / JIT", q:"A manufacturing plant implements a \"pull system\" based on TPS principles. What is the primary objective of this system?", options:["To maximize the production of components to ensure there are no stockouts.","To produce goods in large batches to achieve economies of scale.","To empower workers to stop the production line whenever they detect a defect.","To produce only what is needed by the next process in the production flow, driven by actual customer demand."], answer:3, explain:"A pull system (JIT) triggers production only from real downstream demand — the opposite of push/forecast-driven batch production."},
  {topic:"TPS / Lean / JIT", q:"Which scenario best exemplifies the TPS concept of Jidoka (autonomation)?", options:["A company installs a fully automated robotic arm that operates 24/7 without any human oversight.","An assembly line machine is equipped with a sensor that automatically stops the machine and alerts an operator if it detects a malfunction.","A manager implements a suggestion box where employees can submit ideas for process improvements.","The company cross-trains employees to perform multiple tasks, increasing workforce flexibility."], answer:1, explain:"Jidoka = automation with a human touch: a machine detects an abnormality and stops itself, alerting a human — quality built into the process."},
  {topic:"TPS / Lean / JIT", q:"A factory producing several models implements Heijunka. Which best represents this?", options:["Producing one model for an entire week before switching to minimize changeover time.","Producing models in the same fixed sequence every day regardless of order fluctuations.","Leveling production by producing a mixed-model sequence each day to match the variety of customer demand.","Prioritizing the most popular model and only producing others when there is spare capacity."], answer:2, explain:"Heijunka levels production by interleaving a representative mix of models daily, matching actual demand variety rather than batching by model."},
  {topic:"TPS / Lean / JIT", q:"The \"Five Whys\" technique is primarily used to:", options:["Brainstorm at least five potential solutions to a problem.","Identify the root cause of a problem by repeatedly asking \"why\".","Assign blame for a problem to five different departments.","Create a five-step plan for implementing a solution."], answer:1, explain:"5 Whys is a root-cause-analysis technique: repeatedly asking why drills past symptoms to the underlying cause."},
  {topic:"TPS / Lean / JIT", q:"What does \"Muri\" refer to in the Toyota Production System's waste framework?", options:["Waste from non-value-adding activity","Unevenness in workload or demand","Overburdening of people or equipment","Waiting time between process steps"], answer:2, explain:"Muri = overburden (pushing people/machines beyond reasonable limits). Muda = waste, Mura = unevenness."},
  {topic:"TPS / Lean / JIT", q:"Converting an \"internal setup\" activity to an \"external setup\" activity means:", options:["Making the setup step slower but more reliable","Performing that setup activity while the machine keeps running, instead of while it is stopped","Outsourcing the setup task to a third-party vendor","Eliminating the setup activity entirely"], answer:1, explain:"External setup = work that can be done while the machine is still running; converting internal→external is the first SMED strategy to cut changeover downtime."},
  {topic:"TPS / Lean / JIT", q:"In the 5S methodology, \"Seiton\" means:", options:["Sort — keep only what's necessary","Straighten / Set in order — a designated place for everything","Shine — clean the workplace","Sustain — maintain discipline over time"], answer:1, explain:"Seiton = Straighten/Set in order (organize so everything has a fixed place). Seiri=Sort, Seiso=Shine, Seiketsu=Standardize, Shitsuke=Sustain."},
  {topic:"TPS / Lean / JIT", q:"Which is one of the two pillars of the Toyota Production System?", options:["Total Quality Management and Six Sigma","Just-in-Time and Jidoka","Kanban and ERP","Outsourcing and Automation"], answer:1, explain:"TPS rests on two pillars: Just-in-Time (JIT) and Jidoka (autonomation)."},
  {topic:"TPS / Lean / JIT", q:"An Andon lamp turning RED on an assembly line signals:", options:["Normal operation, no action needed","A request for supervisor help but the line keeps running","A full line stoppage due to a detected problem","Scheduled maintenance is starting"], answer:2, explain:"Red = line stoppage. Yellow = call for help. Green = normal operation."},

  // ---- Mass Customization ----
  {topic:"Mass Customization", q:"A webstore lets customers design their own sneakers (colors, materials, personalized text); the company manufactures and ships the unique pair. Which type of mass customization is this?", options:["Collaborative Customization","Transparent Customization","Adaptive Customization","Cosmetic Customization"], answer:0, explain:"The firm directly interacts with the customer to co-design a unique product before manufacturing it — this is Collaborative Customization."},
  {topic:"Mass Customization", q:"A hotel automatically gives a returning guest their preferred pillow type based on past stays, without telling them explicitly. This is:", options:["Collaborative Customization","Transparent Customization","Adaptive Customization","Cosmetic Customization"], answer:1, explain:"Transparent customization: the firm customizes based on known customer data without the customer explicitly requesting or being told."},
  {topic:"Mass Customization", q:"An adjustable office chair that customers can reconfigure themselves after purchase illustrates:", options:["Cosmetic Customization","Collaborative Customization","Adaptive Customization","Transparent Customization"], answer:2, explain:"Adaptive customization: the company offers one standard but customizable product, letting the customer alter it themselves."},
  {topic:"Mass Customization", q:"Coca-Cola selling identical bottles but printing different customer names on the label is an example of:", options:["Cosmetic Customization","Adaptive Customization","Transparent Customization","Collaborative Customization"], answer:0, explain:"Cosmetic customization keeps the core product identical, changing only packaging/presentation per customer."},
  {topic:"Mass Customization", q:"Mass customization, compared to mass production, is best associated with:", options:["Long product life cycles and stable, homogeneous demand","Short product life cycles and fragmented, heterogeneous demand","Elimination of all customer involvement in the process","Elimination of product variety to cut costs"], answer:1, explain:"Mass customization targets fragmented/heterogeneous demand with short product life cycles and high variety, requiring customer involvement."},

  // ---- Project Management / CPM ----
  {topic:"Project Management", q:"In project management, what does the 'critical path' represent?", options:["The longest sequence of dependent tasks that determines the minimum time to complete the project.","A list of all the tasks in the project that can be delayed without affecting the project deadline.","The longest possible time in which a project can be completed.","The sequence of tasks that have the most float or slack."], answer:0, explain:"The critical path is the longest chain of dependent activities, and it fixes the minimum possible project duration."},
  {topic:"Project Management", q:"What is the total slack of an activity on the critical path?", options:["It depends on the duration of the activity.","It is always zero.","It is always positive.","It is always negative."], answer:1, explain:"By definition, critical-path activities have zero slack — any delay to them delays the whole project."},
  {topic:"Project Management", q:"The 'backward pass' in CPM is used to calculate:", options:["Early Start (ES) and Early Finish (EF) times","Late Start (LS) and Late Finish (LF) times","The total project budget","The number of resources required"], answer:1, explain:"Forward pass → ES/EF (left to right). Backward pass → LS/LF (right to left, from project end back to start)."},
  {topic:"Project Management", q:"When crashing a project to shorten its duration, which activities should you crash first?", options:["Any activity, regardless of whether it is on the critical path","Only critical-path activities, starting with the lowest cost slope","Only the longest-duration activity in the whole project","Non-critical activities with the most slack"], answer:1, explain:"Only shortening critical-path activities reduces project duration, and among those you pick the cheapest (lowest cost-slope) option first."},
  {topic:"Project Management", q:"Cost slope for crashing an activity is calculated as:", options:["Normal Cost / Normal Time","(Crash Cost − Normal Cost) / (Normal Time − Crash Time)","(Normal Time − Crash Time) / (Crash Cost − Normal Cost)","Crash Cost × Crash Time"], answer:1, explain:"Cost slope = extra cost per unit time saved = (Crash Cost − Normal Cost) / (Normal Time − Crash Time)."},
  {topic:"Project Management", q:"If two parallel paths both become critical after some crashing, to shorten the project by one more week you generally need to:", options:["Crash any single activity on either path","Crash an activity on EACH critical path simultaneously (or a shared activity), whichever is cheaper", "Stop crashing since it's now impossible to shorten further","Crash only the path with the higher total cost"], answer:1, explain:"Once multiple paths are simultaneously critical, shortening only one of them won't reduce project duration — you must shorten all critical paths together (or find one shared activity that covers several)."},
  {topic:"Project Management", q:"Which of these is a project risk category commonly discussed alongside CPM/uncertainty?", options:["Only technology risk matters; others are irrelevant","Financial, Marketing, Technology, and Operations/Execution risks", "Only the project manager's personal risk", "Risk categories don't apply once the critical path is computed"], answer:1, explain:"The four broad risk categories are Financial (penalties, FX), Marketing (demand shifts), Technology (obsolescence/tie-ups), and Operations/Execution (resource/delay risk)."},

  // ---- Terminology / Little's Law ----
  {topic:"Terminology, Little's Law & CODP", q:"Little's Law states that:", options:["Inventory = Throughput ÷ Flow Time","Inventory = Throughput × Flow Time","Flow Time = Throughput × Inventory","Throughput = Inventory × Flow Time"], answer:1, explain:"Little's Law: I = R × T (Inventory = Throughput/Flow-Rate × Flow Time)."},
  {topic:"Terminology, Little's Law & CODP", q:"A claims office processes 10,000 claims/year with an average processing time of 3 weeks (50-week year). Using Little's Law, the average number of claims 'in process' is:", options:["300 claims","600 claims","3,000 claims","166 claims"], answer:1, explain:"I = R × T = 10,000/yr × (3/50 yr) = 600 claims."},
  {topic:"Terminology, Little's Law & CODP", q:"'Utilization' in process analysis is defined as:", options:["Demand ÷ Capacity","Flow Rate ÷ Capacity","Capacity ÷ Flow Rate","Inventory ÷ Flow Time"], answer:1, explain:"Utilization = actual Flow Rate ÷ Capacity (how much of available capacity is actually being used)."},
  {topic:"Terminology, Little's Law & CODP", q:"'Implied Utilization' is defined as:", options:["Flow Rate ÷ Capacity","Capacity ÷ Demand","Demand ÷ Capacity","Inventory ÷ Throughput"], answer:2, explain:"Implied Utilization = Demand ÷ Capacity — it can exceed 100%, signaling the resource cannot keep up with demand."},
  {topic:"Terminology, Little's Law & CODP", q:"A process bottleneck is best described as:", options:["The first step in any process","The resource/step with the LOWEST capacity, limiting overall system output","The step with the highest inventory","A step that never changes once identified"], answer:1, explain:"The bottleneck is whichever resource has the least capacity relative to the work required of it; note that bottlenecks CAN shift if demand mix changes."},
  {topic:"Terminology, Little's Law & CODP", q:"Cycle Time (CT) is best described as:", options:["The maximum output a system can ever produce","The average time between completion of two successive units (=1/Throughput)","The total time to design a new product","The time a customer waits before an order is even placed"], answer:1, explain:"Cycle time = average time between completions of successive units, i.e., the reciprocal of throughput rate."},
  {topic:"Terminology, Little's Law & CODP", q:"A GM states inventory turns 3 times a year, and everything clears the dock in 6 weeks. Are these statements consistent?", options:["Yes, both imply the same flow time of 6 weeks","No — 3 turns/year implies a flow time of about 17.3 weeks, not 6","Yes, because turnover and flow time are unrelated","Cannot be determined without more information"], answer:1, explain:"Turnover = 1/T, so T = 1/3 year ≈ 17.3 weeks, which contradicts the claimed 6-week flow time."},
  {topic:"Terminology, Little's Law & CODP", q:"Which manufacturing strategy involves designing AND making a product specifically to a customer's unique specification (e.g., custom industrial machinery)?", options:["Make-to-Stock (MTS)","Assemble-to-Order (ATO)","Make-to-Order (MTO)","Engineer-to-Order (ETO)"], answer:3, explain:"ETO involves custom engineering/design work in addition to custom manufacturing — the deepest level of customization."},
  {topic:"Terminology, Little's Law & CODP", q:"The Customer Order Decoupling Point (CODP) separates:", options:["Marketing activities from Finance activities","Forecast/planning-driven upstream activity from actual-demand-driven downstream activity","Domestic operations from international operations","Quality control from production scheduling"], answer:1, explain:"Before the CODP, production is driven by forecasts/planning (make to stock/anticipation); after it, production is driven by the actual customer order."},

  // ---- Layouts & Assembly Line ----
  {topic:"Layouts & Assembly Line", q:"In assembly line balancing, the theoretical minimum number of workstations is calculated as:", options:["Cycle Time ÷ Sum of task times","Sum of task times ÷ Cycle Time","Sum of task times × Cycle Time","Number of tasks ÷ Cycle Time"], answer:1, explain:"Theoretical minimum workstations N = ΣTask times / Cycle Time (rounded up)."},
  {topic:"Layouts & Assembly Line", q:"Line efficiency in assembly-line balancing is calculated as:", options:["ΣTask times ÷ (Actual workstations × Cycle Time)","(Actual workstations × Cycle Time) ÷ ΣTask times","Cycle Time ÷ ΣTask times","Number of workstations ÷ Number of tasks"], answer:0, explain:"Efficiency = ΣTask times / (Actual number of workstations × Cycle Time); Balance Delay = 1 − Efficiency."},
  {topic:"Layouts & Assembly Line", q:"Which layout arranges equipment in the exact sequence of production steps, with the product moving from one station to the next?", options:["Process Layout","Product Layout","Fixed-Position Layout","Cellular Layout"], answer:1, explain:"Product layout follows the production sequence station-by-station, e.g. a car assembly line."},
  {topic:"Layouts & Assembly Line", q:"A hospital, where similar equipment/specialties are grouped into departments and patients move between departments as needed, is an example of:", options:["Product Layout","Process Layout","Cellular Layout","Fixed-Position Layout"], answer:1, explain:"Process layout groups similar functions/machines together; the flow unit moves to whichever department it needs next."},
  {topic:"Layouts & Assembly Line", q:"Building a ship or an aircraft, where the product stays in one place and workers/equipment come to it, is an example of:", options:["Product Layout","Process Layout","Cellular Layout","Fixed-Position Layout"], answer:3, explain:"Fixed-position layout: the (typically large/immobile) product stays put; labor and resources move to it."},
  {topic:"Layouts & Assembly Line", q:"Available Labour Time on an assembly line is calculated as:", options:["Number of workers × Cycle Time","Number of workers ÷ Cycle Time","Labour Content × Number of workers","Cycle Time ÷ Number of workers"], answer:0, explain:"Available Labour Time = Number of workers × Cycle Time."},
  {topic:"Layouts & Assembly Line", q:"A disadvantage of high labor specialization on an assembly line, FROM THE WORKER's perspective, is:", options:["Difficulty recruiting new staff","Boredom and little control over work pace, leading to fatigue","Higher wages due to skill requirements","Increased flexibility to switch tasks"], answer:1, explain:"For labor, specialization's downsides include boredom, low control over pace, and little opportunity for advancement."},
  {topic:"Layouts & Assembly Line", q:"In line balancing with zoning constraints, if a workstation combines a Junior-Operator task and a Senior-Tailor task, what personnel does that workstation require?", options:["Junior Operator, since most tasks are simple","Senior Tailor, since a workstation takes the skill level of its highest-skilled task","Either, chosen at random each day","Two workers, one of each type, always"], answer:1, explain:"A workstation's required skill = the highest-skilled task assigned to it (a senior worker can do junior tasks, but not vice-versa)."},

  // ---- Capacity Management ----
  {topic:"Capacity Management", q:"For a custom, made-to-order business (e.g., bespoke tailoring), the generally recommended capacity strategy is to:", options:["Lag demand to minimize risk","Lead demand and stay flexible","Ignore capacity planning entirely","Always operate at 100% utilization"], answer:1, explain:"Custom/low-volume operations should generally lead demand to avoid losing custom orders and to capture market share early, since flexibility (not scale efficiency) is the priority."},
  {topic:"Capacity Management", q:"For a standardized, high-volume, made-to-stock commodity (e.g., bottled water), the generally recommended capacity strategy is to:", options:["Lead demand aggressively","Lag demand, expanding only once demand is confirmed","Randomize expansion timing","Never expand capacity"], answer:1, explain:"Standardized high-volume products benefit from lagging demand — expanding only once growth is confirmed, keeping a low-cost focus."},
  {topic:"Capacity Management", q:"'Diseconomies of scale' refers to:", options:["Average unit cost continuing to fall no matter how large the operation grows","Average unit cost beginning to rise again once a business grows beyond its optimal size","A situation where fixed costs disappear entirely","Average cost always being independent of scale"], answer:1, explain:"Beyond an optimal size, complexity/coordination costs can make average unit cost rise again — diseconomies of scale."},
  {topic:"Capacity Management", q:"Which capacity decision belongs to the SHORT-RANGE time horizon?", options:["Building a new factory","Scheduling jobs and staff on existing equipment","Subcontracting extra production for the quarter","Buying long-lead-time equipment"], answer:1, explain:"Short-range planning uses EXISTING capacity better (job/staff scheduling); it doesn't change capacity itself."},
  {topic:"Capacity Management", q:"During the DECLINE stage of a product's life cycle, the typical capacity/operations focus is:", options:["Aggressively expanding capacity to capture growth","Cost control, since the industry often has excess capacity and weak products get cut","Frequent design changes and short production runs","Ignoring cost and focusing purely on availability"], answer:1, explain:"In decline, sales fall, the industry typically has too much capacity, and firms focus on cost control and pruning weak products."},

  // ---- Product/Service-Process Matrix ----
  {topic:"Process Matrix", q:"A bakery that makes 100 chocolate cakes, changes setup, then makes 100 vanilla cakes is an example of:", options:["Job shop production","Batch production","Mass production","Continuous production"], answer:1, explain:"Batch production processes discrete groups (batches) of a product before switching over to the next."},
  {topic:"Process Matrix", q:"An oil refinery running 24/7 with very little product variety exemplifies:", options:["Job shop","Batch process","Mass production","Continuous process"], answer:3, explain:"Continuous process: very high volume, minimal variety, runs around the clock — refineries, cement plants."},
  {topic:"Process Matrix", q:"In the Product-Process Matrix, moving from Job Shop toward Continuous Process generally corresponds to:", options:["Decreasing volume, increasing customization","Increasing volume, increasing standardization","No change in volume or standardization","Decreasing standardization at constant volume"], answer:1, explain:"The matrix's diagonal moves from low-volume/high-customization (job shop) to high-volume/high-standardization (continuous process)."},
  {topic:"Process Matrix", q:"In the Service-Process Matrix, a hospital or auto-repair shop (low labor intensity, high customer interaction/customization) is classified as:", options:["Service Factory","Service Shop","Mass Service","Professional Service"], answer:1, explain:"Service Shop = low labor intensity + high customer interaction/customization (hospitals, auto repair)."},

  // ---- Supplier Relationships ----
  {topic:"Supplier Relationships", q:"Toyota's approach to supplier relationships (Keiretsu model) is best characterized by:", options:["Short-term contracts awarded purely on lowest price","Long-term partnership, trust, and mutual knowledge-sharing","Frequently switching suppliers to maximize leverage","Withholding all information from suppliers to protect trade secrets"], answer:1, explain:"Toyota treats suppliers as long-term partners (Keiretsu), building trust and sharing knowledge — very different from adversarial, price-only vendor management."},
  {topic:"Supplier Relationships", q:"Traditional/adversarial vendor management is typically characterized by:", options:["Long-term trust-based partnerships","Playing suppliers off against each other mainly on price, with short-term contracts","Toyota-style mutual investment in supplier development","High information sharing across the whole chain"], answer:1, explain:"Traditional vendor management is transactional and price-driven, often pitting suppliers against each other with short-term contracts."},

  // ---- Intro to OM ----
  {topic:"Intro to OM", q:"Which historical milestone is correctly paired with its originator?", options:["Moving assembly line — Henry Gantt (1913)","Division of labor — Adam Smith (1776)","Time and motion studies — Frederick Taylor (1911)","Interchangeable parts — James Watt (1790)"], answer:1, explain:"Division of labor = Adam Smith (1776). Moving assembly line = Henry Ford (1913). Time & motion studies = Gilbreths (1911). Interchangeable parts = Eli Whitney (1790)."},
  {topic:"Intro to OM", q:"Which of these is NOT one of the three major functions common to every organization, per OM theory?", options:["Marketing","Operations","Finance/Accounting","Legal/Compliance"], answer:3, explain:"The three classic organizational functions taught in OM are Marketing, Operations, and Finance/Accounting."},
  {topic:"Intro to OM", q:"'All processes can be improved' is which OM premise?", options:["Premise 1","Premise 2","Premise 3","Premise 4"], answer:1, explain:"Premise 1: All work is a process. Premise 2: All processes can be improved. Premise 3: improved via better/faster/cheaper/stronger. Premise 4: value added to stakeholders."},
  {topic:"Intro to OM", q:"On the responsiveness-vs-productivity efficiency frontier, 'redesigning operations to improve performance along multiple dimensions simultaneously' means:", options:["Picking a different trade-off point on the same frontier","Pushing the frontier itself outward, rather than just moving along it","Ignoring productivity in favor of responsiveness","Reducing both responsiveness and productivity together"], answer:1, explain:"Moving along the frontier is a trade-off; redesigning the process to beat the current frontier on both dimensions at once is the more ambitious improvement."},
  {topic:"Intro to OM", q:"Which pair correctly matches a competitive priority with its OM example?", options:["Cost leadership — Sony's constant product innovation","Differentiation — IndiGo's no-frills service","Response/speed — Domino's 30-minute delivery guarantee","Quality — FedEx's 'absolutely, positively on time'"], answer:2, explain:"Domino's 30-minute guarantee is a speed/response example. Sony=differentiation (innovation), IndiGo=cost leadership, FedEx=dependability/response."},

  // ---- Terminology, Little's Law & CODP ----
  {topic:"Terminology, Little's Law & CODP", q:"A company chooses to hold pre-built standard sub-assemblies and only does final assembly after the customer orders — this is:", options:["Make-to-Stock (MTS)","Assemble-to-Order (ATO)","Make-to-Order (MTO)","Engineer-to-Order (ETO)"], answer:1, explain:"ATO: standard components are built in advance; only final assembly happens after the order is placed."},
  {topic:"Terminology, Little's Law & CODP", q:"Moving the Customer Order Decoupling Point further UPSTREAM (earlier in the process) generally:", options:["Increases delivery lead time to the customer but reduces finished-goods inventory risk","Has no effect on inventory or lead time","Always increases both inventory risk and lead time","Eliminates the need for any forecasting"], answer:0, explain:"Pushing the DP upstream (toward MTO/ETO) means less is pre-built to stock, cutting finished-goods inventory risk, but the customer waits longer since more work happens after the order arrives."},
  {topic:"Terminology, Little's Law & CODP", q:"Deciding to open a new factory is an example of which level of decision-making?", options:["Operational (day-to-day)","Tactical (6 months–2 years)","Strategic (3–5+ years)","None of these — it's a marketing decision"], answer:2, explain:"Opening a new factory is a major, slow-to-reverse commitment — a strategic decision, typically with a 3–5+ year horizon."},

  // ---- Supplier Relationships ----
  {topic:"Supplier Relationships", q:"In the Toyota Way, before scaling up to a permanent supplier relationship, Toyota often:", options:["Signs an exclusive lifetime contract immediately","Tests the supplier's commitment through smaller orders first","Refuses to share any performance expectations","Requires the supplier to underbid all competitors"], answer:1, explain:"Toyota Way Principle 11 (respect & develop suppliers): commitment is often tested with smaller orders before a full long-term partnership is built."},
  {topic:"Supplier Relationships", q:"A company that frequently switches suppliers purely to extract the lowest price, using short-term contracts, is practicing:", options:["Keiretsu partnership","Traditional/adversarial vendor management","Genchi Genbutsu","Heijunka-based sourcing"], answer:1, explain:"Playing suppliers off against each other on price with short-term contracts is the hallmark of traditional/adversarial vendor management."},
  {topic:"Supplier Relationships", q:"Which best describes a key benefit Toyota gains from long-term, trust-based supplier partnerships (vs. adversarial sourcing)?", options:["Lower supplier accountability since contracts are informal","Mutual knowledge-sharing and supplier co-development that improves quality and innovation over time","Guaranteed lowest unit price on every part, every year","No further need to monitor supplier performance"], answer:1, explain:"Long-term trust enables knowledge-sharing and joint improvement — Toyota still holds suppliers to high standards, but invests in helping them meet those standards."},

  // ---- Worked Numericals ----
  {topic:"Worked Numericals", q:"In an inventory build-up (queueing) diagram, the vertical gap between the cumulative-arrivals curve and the cumulative-departures curve at a given time represents:", options:["The total capacity of the system","The instantaneous queue/inventory at that time","The average flow time for all units","The bottleneck's location"], answer:1, explain:"The vertical gap between cumulative arrivals and cumulative departures at any instant equals the number of units currently waiting/in the system (instantaneous inventory)."},
  {topic:"Worked Numericals", q:"In the same diagram, the HORIZONTAL gap between the two curves for a specific unit represents:", options:["That unit's processing capacity","That unit's individual wait/flow time in the system","The system's bottleneck rate","The total number of units processed that day"], answer:1, explain:"The horizontal distance from a unit's arrival point to when the cumulative-departures curve reaches that same count is exactly that unit's time-in-system."},
  {topic:"Worked Numericals", q:"A machine has a fixed setup time before each batch, plus a run time per unit. If you DOUBLE the batch size (setup time unchanged), the effective capacity (units/time) will:", options:["Decrease, since the batch takes longer to finish","Increase, since the fixed setup cost is spread over more units","Stay exactly the same","Become zero"], answer:1, explain:"Effective Capacity = Batch size / (Setup + Batch size × Run time). Larger batches amortize the fixed setup over more units, raising effective throughput capacity."},
  {topic:"Worked Numericals", q:"Using larger process batches to raise a resource's effective capacity typically comes at the cost of:", options:["Lower flow rate","Higher average WIP/inventory and longer flow time (by Little's Law)","No trade-off at all — it is a pure win","Reduced setup time"], answer:1, explain:"Bigger batches mean units wait longer for a full batch to complete/move, raising average inventory and flow time (I = R×T) even as raw capacity rises."},
  {topic:"Worked Numericals", q:"When a shared resource's capacity is 'used by multiple products,' the true bottleneck of the system is determined by:", options:["Simply the resource with the largest machine","Each resource's capacity in isolation, ignoring product mix","Each resource's capacity accounting for the ACTUAL product mix flowing through it","Whichever resource is physically first in the process"], answer:2, explain:"A resource that looks fine in isolation can become the real bottleneck once you account for how much of its time the actual demand mix consumes."},

  // ---- Layouts & Assembly Line (extra) ----
  {topic:"Layouts & Assembly Line", q:"Process Batch and Transfer Batch differ in that:", options:["They are always identical in size","Process batch = units processed together at a stage; Transfer batch = units physically moved together to the next stage (can be smaller)","Transfer batch is always larger than process batch","Neither concept relates to flow time"], answer:1, explain:"Using a smaller transfer batch than the process batch lets stages overlap, reducing overall flow time — a key lean lever independent of the process batch size."},
  {topic:"Layouts & Assembly Line", q:"A U-shaped assembly line, compared to a straight-line design, typically offers:", options:["No advantages — it is purely a cosmetic layout choice","Easier rebalancing and better worker communication, since start and end stations are near each other","Elimination of the need for any cycle-time calculation","Guaranteed 100% line efficiency"], answer:1, explain:"U-shaped lines let a worker cover stations at both the start and end, improve communication/visibility, and make rebalancing easier when demand changes."},

  // ---- Process Matrix (extra) ----
  {topic:"Process Matrix", q:"A custom furniture workshop making one-off, highly customized pieces in very small quantities is an example of:", options:["Continuous process","Mass production","Job shop","Batch process"], answer:2, explain:"Job shop: very low volume, highly customized/one-off production — the opposite end of the matrix from continuous process."},
];